# Generated by Django 5.2.10 on 2026-02-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='evidence',
            field=models.ImageField(blank=True, null=True, upload_to='violations/'),
        ),
    ]
